apiVersion: v1
kind: Pod
metadata:
  name: nginx-limits-no-restart
spec:
  restartPolicy: Never
  containers:
  - name: web
    image: nginx
    env:
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
