apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cleanup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: test
            command: [ "/bin/bash", "-c" ]
            args: [ "i=0 \n while [ $i -lt 10 ]\ndo \n /bin/echo hola en linea $i\n let i=$i+1 \n sleep 1; done" ]
            image: ubuntu:latest
